version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - 'zookeeper_data:/var/lib/zookeeper'

# Uses YAML anchors
# Uses YAML anchors
  broker1: &broker
    image: confluentinc/cp-kafka:7.4.0
    hostname: broker1
    container_name: broker1
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment: &broker_environment
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    volumes:
      - 'broker1_data:/var/lib/kafka'

  broker2:
    <<: *broker
    hostname: broker2
    container_name: broker2
    ports:
      - "29093:29093"
      - "9093:9093"
      - "9102:9102"
    environment:
      <<: *broker_environment
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:29093,PLAINTEXT_HOST://localhost:9093
    volumes:
      - 'broker2_data:/var/lib/kafka'

  broker3:
    <<: *broker
    hostname: broker3
    container_name: broker3
    ports:
      - "29094:29094"
      - "9094:9094"
      - "9103:9103"
    environment:
      <<: *broker_environment
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:29094,PLAINTEXT_HOST://localhost:9094
    volumes:
      - 'broker3_data:/var/lib/kafka'


  conduktor:
    image: 'conduktor/conduktor-platform:latest'
    ports:
      - 8080:8080
    volumes:
      - 'conduktor_data:/var/conduktor'
    depends_on:
      - broker1
      - broker2
      - broker3

volumes:
    zookeeper_data:
    broker1_data:
    broker2_data:
    broker3_data:
    conduktor_data:
