version: '3.7'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    volumes:
      - 'zookeeper_data:/bitnami'

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    ports:
      - 9092:9092
      - 29092:29092
    volumes:
      - 'kafka_data:/bitnami'
    depends_on:
      - zookeeper

  conduktor:
    image: 'conduktor/conduktor-platform:latest'
    ports:
      - 8080:8080
    volumes:
      - 'conduktor_data:/var/conduktor'

volumes:
  zookeeper_data:
    driver: local
    external: false
  kafka_data:
    driver: local
    external: false
  conduktor_data:
    driver: local
    external: false
